# Generated by Django 5.1.4 on 2024-12-09 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=50)),
                ('address_id', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('customer_id_old', models.SmallIntegerField(blank=True, null=True)),
                ('segment', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('language_id', models.SmallIntegerField()),
                ('original_language_id', models.SmallIntegerField(blank=True, null=True)),
                ('rental_duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.SmallIntegerField()),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_voted_users', models.IntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('special_features', models.TextField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('manager_staff_id', models.SmallIntegerField()),
                ('address_id', models.SmallIntegerField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField()),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appETL.film')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appETL.store')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.SmallIntegerField()),
                ('last_update', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appETL.customer')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appETL.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appETL.store'),
        ),
    ]
